apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQlRwYStYMnVYdHd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBek1UQXdPREE1TURoYUZ3MHpOakF6TURjd09ERTBNRGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURqcFRIM0dJZy9RK0tQaE5RbEx2azlkV2hTa1FOUTRXc0JIdmlwWVlmeDZpeUx4djdUMTNicG9BL0MKT0pFZHp0SVZ0bDg3TjE4UktXUDkwLzYzSnR4dGlhZGdacUxYRU9rQnpsWWNvMU5mVEhaR25yalZSMWcxazMwRApud2g0M1cwNDBWekNwbzI2Sy94LzZFdjREZlhyK0dHdnFZeVA0Z2wyd09CTStzdWJYUWhmWWlidjRPY0FuYnRRCkpHeSswYkpSell1T09ydE1pc3RCemRiUFRHNUtwWERiRUg3WDdKSmJLeFpsS0ZoczhQd0JPcUFmUy9XVzlFcEYKbFpSWXZyZWtaTDFBMk5GWlBhSjNET294cFdMbnlEbWMzYWJyL1NOUzRWSGRxMDFQODlxazR2T1RMNStEWjk3bApaQUJWdCthSGxGWUh3SWtvR29Ja3d1MUVjOFdWQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWXlZbkx6TTh0bjJlRUZuRSsyMEQ2NW5XMWVUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnZKbERIS0ZoZApCUE4wVytYVWN6R2ROejFBSUNWNHB3OGtUaEFCUVRsSEFRcnNBc24waloxcGRXaXIwYnZhYzFCeGJTZ29rVnl3CmpVdmtvVktWSmx6OWVVOWxWZlluSCtsRkhnZFZsNEJsbUVVaVFlaHBTVFNtQlhuQWlCdG1kNDM3VGtsVGQ4dUEKdkxQd0w2dnJqQi9pa1FuYmFaUmowTWpzdjJuTFhRNzNselQ5b3diVk9jZTFEM0tXL3N3eU1BN2dpeVRiWllabgpKRnhSMzFjWDVPTENYcXhyUHQ1N3JhUXlsRzB3NmttNEc1YmVwMy8wWXpXU040ZXk3SnBwNzliMVk4b1dnK1hCCjdwRm5sY2NRcWdRdDhtejYwdUtsdHM0Q2l1WUlQRC8zeklPTkp2d1VVNDFCbTRWQTNUZGV6d1N0UTJlWjVHaWkKL3l5cmdKdXRvZXZTCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://D8C138D6E5A149FBAFC8656751026E1D.gr7.eu-north-1.eks.amazonaws.com
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: /usr/local/bin/aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "demo-cluster"
